{{- define "jenkins.svc" }}

apiVersion: v1
kind: Service
metadata:
  name: jenkins-agent
  labels:
    "app.kubernetes.io/component": jenkins
    "app.kubernetes.io/name": kubeops
    "app.kubernetes.io/instance": kubeops-jenkins
spec:
  ports:
    - port: 50000
      targetPort: 50000
      name: agent-listener
  selector:
    "app.kubernetes.io/component": jenkins
    "app.kubernetes.io/name": kubeops
    "app.kubernetes.io/instance": kubeops-jenkins
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins
  labels:
    "app.kubernetes.io/component": jenkins
    "app.kubernetes.io/name": kubeops
    "app.kubernetes.io/instance": kubeops-jenkins
spec:
  ports:
    - port: 80
      name: http
      targetPort: 8080
  selector:
    "app.kubernetes.io/component": jenkins
    "app.kubernetes.io/name": kubeops
    "app.kubernetes.io/instance": kubeops-jenkins
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jenkins
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  labels:
    "app.kubernetes.io/component": jenkins
    "app.kubernetes.io/name": kubeops
    "app.kubernetes.io/instance": kubeops-jenkins
spec:
  ingressClassName: nginx
  rules:
    - host: jenkins.leryn.top
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: jenkins
                port:
                  number: 80
---
{{- end }}
