{{- define "jenkins.rbac" }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jenkins-schedule-agents
rules:
  - apiGroups:
      - ""
    resources:
      - "pods"
      - "pods/exec"
      - "pods/log"
      - "persistentvolumeclaims"
      - "events"
    verbs: ["get", "list", "watch"]
  - apiGroups:
      - ""
    resources:
      - "pods"
      - "pods/exec"
      - "persistentvolumeclaims"
    verbs:
      - "create"
      - "delete"
      - "deletecollection"
      - "patch"
      - "update"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jenkins-casc-reload
rules:
  - apiGroups:
      - ""
    resources:
      - "configmaps"
    verbs:
      - "get"
      - "watch"
      - "list"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-schedule-agents
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jenkins-schedule-agents
subjects:
  - kind: ServiceAccount
    name: {{ include "_api.rbac.serviceAccount.name" . }}
---
# Source: jenkins/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-watch-configmaps
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jenkins-casc-reload
subjects:
  - kind: ServiceAccount
    name: {{ include "_api.rbac.serviceAccount.name" . }}
{{- end }}